<?php
// Vietnamese product names organized by catalogue_id
// Keys match product_catalogues.id
return [
    2 => [ // Thời trang nam
        'Áo Polo Nam Thể Thao ProMax S1',
        'Áo Polo Nam Café Đen',
        'Áo Polo Nam ExCool Thoáng Mát',
        'Áo Sơ Mi Nam Dài Tay Oxford',
        'Áo Thun Nam Cổ Tròn Cotton 100%',
        'Quần Jeans Nam Slim Fit',
        'Quần Kaki Nam Ống Đứng',
        'Áo Khoác Gió Nam Chống Nước',
        'Áo Hoodie Nam Nỉ Bông',
        'Quần Short Nam Thể Thao',
        'Áo Vest Nam Công Sở',
        'Quần Âu Nam Ống Suông',
        'Áo Len Nam Cổ Lọ',
        'Áo Polo Nam Pique Basic Cotton',
        'Quần Jogger Nam Thun Co Giãn',
        'Áo Thun Nam Oversize Unisex',
        'Áo Sơ Mi Nam Caro Ngắn Tay',
        'Quần Jeans Nam Rách Gối',
        'Áo Khoác Bomber Nam',
        'Áo Polo Nam Phối Sọc',
        'Quần Short Kaki Nam',
        'Áo Thun Nam Phông Rộng',
        'Áo Sơ Mi Linen Nam',
        'Quần Tây Nam Ống Côn',
        'Áo Polo Nam Coolmax Dry Fit',
        'Áo Khoác Jean Nam Vintage',
        'Quần Jogger Kaki Nam',
        'Áo Tanktop Nam Tập Gym',
        'Áo Polo Nam Phối Màu Thể Thao',
        'Set Quần Áo Thể Thao Nam',
        'Áo Thun Dài Tay Nam',
        'Quần Jean Nam Baggy',
        'Áo Cardigan Len Nam',
        'Áo Polo Dài Tay Nam',
        'Quần Short Jean Nam',
        'Áo Khoác Dù Hai Lớp Nam',
        'Áo Thun Polo Nam Trơn',
        'Quần Lửng Nam Kaki',
        'Áo Blazer Nam Casual',
        'Combo 3 Áo Polo Nam ProMax',
        'Pack 3 Áo Polo Pique Cotton',
    ],
    3 => [ // Điện thoại & Phụ kiện
        'Ốp Lưng iPhone 15 Pro Max Silicone',
        'Cáp Sạc Nhanh USB-C 65W',
        'Kính Cường Lực Samsung Galaxy S24',
        'Tai Nghe Bluetooth TWS Pro',
        'Sạc Dự Phòng 20000mAh PD 65W',
        'Ốp Lưng Samsung Galaxy S24 Ultra',
        'Gậy Selfie Bluetooth Gập Gọn',
        'Bao Da Flip Cover Galaxy Z Fold',
        'Cáp Lightning Bọc Dù 2m',
        'Củ Sạc Nhanh 3 Cổng GaN 65W',
        'Kính Cường Lực Full Màn iPhone',
        'Đế Sạc Không Dây MagSafe 15W',
        'Ốp Lưng Xiaomi 14 Trong Suốt',
        'Miếng Dán PPF Tự Phục Hồi',
        'Ring Holder Điện Thoại Kim Loại',
        'Túi Đựng Điện Thoại Chống Nước',
        'Adapter OTG USB-C to USB-A',
        'Bút Cảm Ứng Stylus Pen',
        'Giá Đỡ Điện Thoại Ô Tô',
        'Kẹp Điện Thoại Xe Máy Chống Sốc',
    ],
    4 => [ // Thiết bị điện tử
        'Loa Bluetooth Mini Bass Mạnh',
        'Camera An Ninh WiFi 4K',
        'Đèn LED Thông Minh RGB WiFi',
        'Ổ Cắm Thông Minh WiFi',
        'Chuông Cửa Camera AI',
        'Máy Lọc Không Khí Phòng Ngủ',
        'Robot Hút Bụi Lau Nhà Tự Động',
        'Quạt Mini USB Để Bàn',
        'Máy Chiếu Mini HD Portable',
        'Cân Điện Tử Thông Minh Bluetooth',
        'Nhiệt Kế Hồng Ngoại Đo Trán',
        'Máy Đo Huyết Áp Điện Tử',
        'Smart Watch Đo SpO2 Nhịp Tim',
        'Vòng Tay Thông Minh Theo Dõi Sức Khỏe',
        'Máy Massage Cầm Tay',
        'Tai Nghe Chụp Tai ANC',
        'Loa Soundbar TV Bluetooth',
        'Máy Tạo Ẩm Phun Sương',
        'Đèn Bàn LED Chống Cận',
        'Bàn Phím Cơ Gaming RGB',
    ],
    5 => [ // Máy tính & Laptop
        'Chuột Không Dây Wireless 2.4G',
        'Bàn Phím Bluetooth Gập Gọn',
        'Hub USB-C 7 trong 1',
        'Webcam Full HD 1080p',
        'Tai Nghe Gaming 7.1',
        'RAM DDR4 16GB 3200MHz',
        'SSD NVMe 512GB Gen4',
        'Ổ Cứng Di Động 1TB USB-C',
        'Tản Nhiệt Laptop 6 Quạt',
        'Balo Laptop 15.6 inch Chống Sốc',
        'Cáp HDMI 2.1 8K 2m',
        'Màn Hình Portable 15.6 inch',
        'Lót Chuột Gaming XXL RGB',
        'USB Flash Drive 128GB 3.0',
        'Card Đồ Họa GTX 1660 Super',
        'Bộ Chia USB 3.0 4 Cổng',
        'Dây Cáp Mạng LAN Cat6',
        'Giá Đỡ Laptop Nhôm Gấp Gọn',
        'Bộ Vệ Sinh Laptop 8 Món',
        'Adapter WiFi USB AC1300',
    ],
    6 => [ // Thời trang nữ
        'Đầm Suông Công Sở Tay Lỡ',
        'Áo Kiểu Nữ Cổ V Voan',
        'Chân Váy Xếp Ly Midi',
        'Set Đồ Bộ Nữ Mặc Nhà',
        'Áo Croptop Nữ Thể Thao',
        'Quần Culottes Nữ Ống Rộng',
        'Áo Blazer Nữ Oversized',
        'Váy Liền Hoa Nhí Vintage',
        'Quần Legging Nữ Gen Bụng',
        'Áo Len Cardigan Nữ Mỏng',
        'Đầm Maxi Nữ Dự Tiệc',
        'Quần Jeans Nữ Lưng Cao',
        'Áo Sơ Mi Nữ Lụa Satin',
        'Chân Váy Chữ A Ngắn',
        'Set Vest Nữ Công Sở 2 Món',
        'Áo Thun Nữ Baby Tee',
        'Quần Ống Rộng Nữ Kaki',
        'Đầm Sơ Mi Nữ Cổ Đức',
        'Áo Hai Dây Nữ Voan Mỏng',
        'Quần Short Nữ Jeans Rách',
    ],
    7 => [ // Mẹ & Bé
        'Bình Sữa Chống Sặc 260ml',
        'Tã Dán Trẻ Sơ Sinh Size NB',
        'Xe Đẩy Em Bé Gấp Gọn',
        'Ghế Ăn Dặm Đa Năng',
        'Bộ Đồ Chơi Xếp Hình Gỗ',
        'Túi Đựng Bỉm Sữa Đa Năng',
        'Máy Hâm Sữa Tiệt Trùng',
        'Khăn Ướt Em Bé 80 Tờ',
        'Nôi Điện Tự Động Ru Ngủ',
        'Gối Chống Trào Ngược Cho Bé',
        'Sữa Bột Công Thức 900g',
        'Bộ Quần Áo Sơ Sinh Cotton',
        'Cũi Gỗ Em Bé Đa Năng',
        'Xe Tập Đi Cho Bé',
        'Balo Mẫu Giáo Hình Thú',
        'Bộ Đồ Dùng Ăn Dặm Silicon',
        'Khăn Tắm Sợi Tre Em Bé',
        'Đồ Chơi Montessori Cho Bé',
        'Máy Hút Sữa Điện Đôi',
        'Kem Chống Hăm Cho Bé',
    ],
    8 => [ // Nhà cửa & Đời sống
        'Hộp Đựng Thực Phẩm Thuỷ Tinh',
        'Bộ Nồi Inox 3 Đáy 5 Món',
        'Chảo Chống Dính Ceramic 28cm',
        'Máy Xay Sinh Tố Đa Năng',
        'Bộ Dao Nhà Bếp 6 Món',
        'Thùng Rác Thông Minh Cảm Ứng',
        'Bộ Ga Giường Cotton 4 Món',
        'Rèm Cửa Sổ Cách Nhiệt',
        'Đèn Ngủ LED Cảm Ứng',
        'Máy Hút Bụi Cầm Tay Mini',
        'Kệ Sách Gỗ 4 Tầng',
        'Gương Trang Điểm LED',
        'Hộp Khăn Giấy Gỗ Tre',
        'Bình Giữ Nhiệt Inox 500ml',
        'Bộ Ly Thuỷ Tinh 6 Chiếc',
        'Thảm Chùi Chân Chống Trượt',
        'Đồng Hồ Treo Tường Vintage',
        'Chậu Cây Trang Trí Sứ',
        'Móc Treo Quần Áo Gỗ',
        'Bộ Khăn Tắm Cotton 3 Chiếc',
    ],
    9 => [ // Sắc đẹp
        'Son Môi Lì Không Trôi',
        'Kem Chống Nắng SPF50+ PA++++',
        'Nước Tẩy Trang Micellar 400ml',
        'Serum Vitamin C Dưỡng Sáng',
        'Mặt Nạ Đất Sét Trà Xanh',
        'Sữa Rửa Mặt Amino Acid',
        'Kem Dưỡng Ẩm Ban Đêm',
        'Toner Hoa Hồng Cân Bằng Da',
        'Son Dưỡng Môi Có Màu SPF15',
        'Bộ Cọ Trang Điểm 12 Cây',
        'Phấn Nước Cushion BB Cream',
        'Tẩy Tế Bào Chết AHA BHA',
        'Dầu Gội Dược Liệu Thảo Mộc',
        'Dầu Xả Phục Hồi Tóc Hư',
        'Xịt Dưỡng Tóc Keratin',
        'Nước Hoa Mini 10ml EDP',
        'Kem Nền Full Coverage',
        'Mascara Cong Mi Không Lem',
        'Phấn Mắt Palette 12 Màu',
        'Bảng Phấn Highlight Contour',
    ],
    10 => [ // Sức khỏe
        'Vitamin C 1000mg Viên Nang',
        'Omega 3 Dầu Cá 1000mg',
        'Viên Uống Collagen Trắng Da',
        'Thuốc Nhỏ Mắt Dưỡng Ẩm',
        'Nhiệt Kế Điện Tử Đầu Mềm',
        'Máy Đo Đường Huyết',
        'Băng Dán Cá Nhân Hộp 100',
        'Nước Muối Sinh Lý 500ml',
        'Khẩu Trang Y Tế 4 Lớp Hộp 50',
        'Gel Rửa Tay Khô Diệt Khuẩn',
        'Máy Massage Cổ Vai Gáy',
        'Đai Lưng Hỗ Trợ Cột Sống',
        'Viên Uống Bổ Sung Canxi D3',
        'Men Vi Sinh Probiotics',
        'Sữa Ensure Gold 850g',
        'Máy Xông Tinh Dầu Siêu Âm',
        'Túi Chườm Nóng Lạnh',
        'Bông Y Tế Tiệt Trùng',
        'Dung Dịch Sát Khuẩn Tay',
        'Kem Bôi Giảm Đau Khớp',
    ],
    11 => [ // Giày dép nữ
        'Giày Cao Gót Mũi Nhọn 7cm',
        'Dép Sandal Nữ Quai Chéo',
        'Giày Búp Bê Nữ Đế Bệt',
        'Giày Thể Thao Nữ Trắng',
        'Dép Lê Nữ Đế Xuồng',
        'Giày Boot Nữ Cổ Thấp',
        'Sandal Nữ Quai Ngang Đế Dày',
        'Giày Slip-On Nữ Lười',
        'Giày Oxford Nữ Da Thật',
        'Dép Xỏ Ngón Nữ Đi Biển',
    ],
    12 => [ // Túi ví nữ
        'Túi Xách Nữ Da PU Thời Trang',
        'Ví Cầm Tay Nữ Dáng Dài',
        'Balo Nữ Mini Đi Học',
        'Túi Đeo Chéo Nữ Dây Xích',
        'Clutch Nữ Dự Tiệc Đính Đá',
        'Túi Tote Nữ Vải Canvas',
        'Ví Ngắn Nữ Bỏ Túi',
        'Túi Đeo Vai Nữ Dáng Baguette',
        'Balo Laptop Nữ 14 inch',
        'Túi Đựng Mỹ Phẩm Du Lịch',
    ],
    14 => [ // Bách hóa online
        'Mì Ăn Liền Hảo Hảo Thùng 30',
        'Nước Mắm Phú Quốc 500ml',
        'Dầu Ăn Tường An 5 Lít',
        'Gạo ST25 Túi 5kg',
        'Cà Phê Rang Xay Nguyên Chất 500g',
        'Trà Xanh Thái Nguyên 200g',
        'Sữa Tươi TH True Milk Thùng 48',
        'Bánh Tráng Phơi Sương Tây Ninh',
        'Tương Ớt Sriracha 520g',
        'Hạt Điều Rang Muối Bình Phước',
        'Bột Giặt OMO Matic 6kg',
        'Nước Xả Vải Comfort 3.8L',
        'Nước Rửa Chén Sunlight 3.8kg',
        'Giấy Vệ Sinh Pulppy 12 Cuộn',
        'Khăn Giấy Kleenex Hộp 100',
        'Dầu Oliu Extra Virgin 1L',
        'Mật Ong Nguyên Chất 500ml',
        'Hạt Macca Đắk Lắk 500g',
        'Nước Tương Maggi 700ml',
        'Bột Mì Đa Dụng 1kg',
    ],
    17 => [ // Đồng hồ
        'Đồng Hồ Nam Dây Thép Automatic',
        'Đồng Hồ Nữ Dây Da Mặt Tròn',
        'Đồng Hồ Thể Thao Casio G-Shock',
        'Đồng Hồ Đôi Valentine',
        'Đồng Hồ Điện Tử Trẻ Em',
        'Đồng Hồ Nam Chronograph 6 Kim',
        'Đồng Hồ Nữ Lắc Tay Sang Trọng',
        'Đồng Hồ Thông Minh Amoled',
        'Đồng Hồ Nam Mặt Vuông Dây Lưới',
        'Đồng Hồ Treo Tường Gỗ Tự Nhiên',
    ],
    18 => [ // Giày dép nam
        'Giày Thể Thao Nam Air Cushion',
        'Giày Da Nam Công Sở',
        'Dép Quai Ngang Nam Đế Dày',
        'Giày Sneaker Nam Cổ Cao',
        'Dép Sandal Nam Đi Biển',
        'Giày Lười Nam Da Bò Thật',
        'Boot Nam Cổ Cao Da Thật',
        'Giày Chạy Bộ Nam Siêu Nhẹ',
        'Dép Xỏ Ngón Nam Cao Su',
        'Giày Bóng Đá Nam TF Sân Cỏ Nhân Tạo',
    ],
    19 => [ // Thiết bị điện gia dụng
        'Máy Giặt Cửa Trước 9kg Inverter',
        'Tủ Lạnh Side By Side 600L',
        'Điều Hòa 2 Chiều Inverter 12000BTU',
        'Nồi Cơm Điện Tử 1.8L',
        'Máy Lọc Nước RO 10 Lõi',
        'Bình Nóng Lạnh 30L',
        'Bếp Từ Đôi Hồng Ngoại',
        'Máy Xay Đa Năng 3 trong 1',
        'Lò Vi Sóng Có Nướng 25L',
        'Bàn Ủi Hơi Nước 2400W',
    ],
    20 => [ // Thể thao & Du lịch
        'Vợt Cầu Lông Carbon Siêu Nhẹ',
        'Bóng Rổ Spalding Size 7',
        'Thảm Yoga TPE 6mm Chống Trượt',
        'Túi Du Lịch Vải Bố 40L',
        'Lều Cắm Trại 4 Người',
        'Bình Nước Thể Thao 750ml',
        'Bộ Tạ Tay 20kg Bọc Cao Su',
        'Giày Đá Bóng Sân Cỏ',
        'Balo Leo Núi 50L Chống Nước',
        'Kính Bơi Chống Sương Mù',
    ],
    21 => [ // Ô tô & Xe máy & Xe đạp
        'Nước Rửa Kính Xe Ô Tô 5L',
        'Bọc Ghế Da Ô Tô 5 Chỗ',
        'Camera Hành Trình 4K WiFi',
        'Máy Bơm Lốp Ô Tô 12V',
        'Nước Hoa Xe Ô Tô Treo Gương',
        'Dầu Nhớt Xe Máy Synthetic 1L',
        'Bao Tay Lái Xe Máy Chống Nắng',
        'Khóa Chống Trộm Xe Máy',
        'Gương Chiếu Hậu Xe Đạp',
        'Đèn Pha LED Xe Đạp Sạc USB',
    ],
];
